export const UPDATE_REGION_FILTER = 'UPDATE_REGION_FILTER';
export const UPDATE_GENDER_FILTER = 'UPDATE_GENDER_FILTER';
export const UPDATE_YEAR_FILTER = 'UPDATE_YEAR_FILTER';
export const UPDATE_DATA = 'UPDATE_DATA';
